name: Update Metapackages

on:
  push:
    branches:
      - bionic

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
    - name: Update metapackages
      run: ./update_metapackages.sh bionic